# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LearnRxSwiftSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnRxSwiftSampleApp

  target 'LearnRxSwiftSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearnRxSwiftSampleAppUITests' do
    # Pods for testing
  end

pod 'RxSwift'
pod 'RxCocoa'

end
